version: '3'

services:
  backend:
    build: ./backend/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/code/
    ports: 
      - "8000:8000"
    depends_on: 
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose: 
      - 3306
