version: "3"

services:
  backend:
    build: ./backend/app/.
    # todo: ここをアプリケーションサーバの立ち上げに変更
    command: python manage.py runserver 0.0.0.0:8000
    # todo:ここはvolumeじゃなくてコピーのほうがいいかも？
    volumes:
      - ./backend/app:/code/
    # todo portsは普通これでいい？
    ports:
      - "8000:8000"
    # depends_on消す？
    depends_on:
      db:
        condition: service_healthy
    #todo:access pointとかもenvいれる？
    environment:
      - ENV=PROD
    #todo:networkあったほうがいい？

  # rds使う場合はここごっそりけしてよい？
  # rdsの設定をbackend/environにいれる？
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  frontend:
    image: node:alpine
    # volumes消す？
    volumes:
      - ./frontend/web-front/:/usr/src/app
    working_dir: /usr/src/app
    # たぶんここはbuildで良さそう？
    command: sh -c "npm install &&npm build"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    # depends_on消す？
    depends_on:
      - backend
      - db
    environment:
      - ENV=PROD
