version: "3"

services:
  backend:
    build: ./backend/app/.
    command: python -B manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app/:/code/
    ports:
      - "8000:8000"
    env_file:
      - backend.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_ENV=development

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  frontend:
    image: node:alpine
    volumes:
      - ./frontend/web-front/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install &&npm start"
    # command: sh -c "ls"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
      - db
