## 本番環境の内、手元でビルドするもの

version: "3"
services:
  frontend:
    image: node:alpine
    volumes:
      - ./frontend/web-front/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run build"
    tty: true
