version: "3"
#memo
# nginxをリバースプロキシで使う場合、フロントとバックそれぞれにwebサーバなくてもいいかも
services:
  backend:
    image: koheikujira/quiz_app-backend:latest
    # todo: ここをアプリケーションサーバの立ち上げに変更
    command: gunicorn -w 4 quizProject.wsgi:application --bind 0.0.0.0:8000 --chdir /code/quizProject
    # todo:ここはvolumeじゃなくてコピーのほうがいいかも？
    volumes:
      - ./backend/app:/code/
    # todo portsは普通これでいい？
    ports:
      - "8000:8000"
    #todo:access pointとかもenvいれる？
    environment:
      - ENV=PROD
    #todo:networkあったほうがいい？

  frontend:
    image: node:alpine
    # volumes消す？
    volumes:
      - ./frontend/web-front/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run build"
    ports:
      - "3000:3000"
    tty: true
    # stdin_open: true
    environment:
      - ENV=PROD

  nginx:
    image: nginx:1.13
    # build: ./nginx/.
    # for frontend build folder
    volumes:
      - ./frontend/web-front/build:/usr/share/nginx/html
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend
      # frontend:
      #   condition: service_completed_successfully
