##　本番環境の内、実際にサーバ内で実行するもの

version: "3"
services:
  backend:
    image: koheikujira/quiz_app-backend:latest
    command: gunicorn -w 4 quizProject.wsgi:application --bind 0.0.0.0:8000 --chdir /code/quizProject
    volumes:
      - ./backend/app:/code/
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
    env_file:
      - backend.env

  nginx:
    image: nginx:1.13
    # build: ./nginx/.
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend
